---
apiVersion: v2
name: global-domain-MIGRATION_ID
description: Canton Network Super Validator - NETWORK - global-domain
type: application
version: 1.0.0

dependencies:
  - name: splice-global-domain
    version: "CHART_VERSION"
    repository: "oci://ghcr.io/digital-asset/decentralized-canton-sync/helm"
    alias: global-domain
  - name: canton-validator-template
    version: "TEMPLATE_VERSION"
    repository: "file://../../templates/canton-validator-template"
    alias: template
