{{- if $.Values.deployment }}
{{- $selectorValue := printf "%s" $.Values.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.name }}
  namespace: {{ $.Values.namespace | quote }}
  labels:
    {{- with $.Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "service.labels" $ | nindent 4 }}
    app.kubernetes.io/instance: {{ $selectorValue }}
  {{- with $.Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $selectorValue }}
  {{- if $.Values.strategy }}
  strategy:
    type: {{ $.Values.strategy }}
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ $selectorValue }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $.Values.name }}
          {{- if $.Values.command }}
          command: {{ $.Values.command | toJson }}
          {{- end }}
          {{- if $.Values.args }}
          args: {{ $.Values.args | toJson }}
          {{- end }}
          image: "{{ $.Values.imageRepository }}:{{ $.Values.imageTag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          {{- if $.Values.env }}
          env:
            {{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              value: {{ (tpl ($value | toString) $) | quote }}
            {{- end }}
            {{- if $.Values.envFieldRef }}
            {{- range $key, $value := $.Values.envFieldRef }}
            - name: {{ $key }}
              valueFrom:
                fieldRef:
                 fieldPath: {{ $value }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- if $.Values.service.ports }}
          ports:
            {{- range $port := $.Values.service.ports }}
            - name: {{ $port.name }}
              containerPort: {{ $port.port }}
              protocol: TCP
            {{- end }}
          {{- end }}
          {{- if $.Values.livenessProbe }}
          livenessProbe:
            {{- toYaml $.Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if $.Values.readinessProbe }}
          readinessProbe:
            {{- toYaml $.Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if $.Values.resources }}
          resources:
          {{- toYaml $.Values.resources | nindent 12 }}
          {{- end }}
          {{- with $.Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $.Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
