{{- range $secret := $.Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $.Values.namespace | default "internal" | quote }}
type: Opaque
data:
{{- range $key, $value := $secret.values }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
