---
template:
  name: utility-ui

  deployment: true

  imagePullSecrets:
    - name: "DA_UTILITY_JFROG_REGCRED"
  imageRepository: DA_UTILITY_IMAGE_LOCATION

  ingress:
    enabled: true

  replicaCount: 1

  resources:
    requests:
      cpu: 0.1
      memory: 240Mi
    limits:
      cpu: 1
      memory: 1536Mi

  strategy: Recreate
