---
apiVersion: v2
name: sv
description: Canton Network Super Validator - NETWORK - sv
type: application
version: 1.0.0

dependencies:
  - name: splice-sv-node
    version: "CHART_VERSION"
    repository: "oci://ghcr.io/digital-asset/decentralized-canton-sync/helm"
    alias: sv
  - name: canton-validator-template
    version: "TEMPLATE_VERSION"
    repository: "file://../../templates/canton-validator-template"
    alias: template

# helm install sv oci://ghcr.io/digital-asset/decentralized-canton-sync/helm/splice-sv-node -n sv --version ${CHART_VERSION} -f splice-node/examples/sv-helm/sv-values.yaml -f ${SV_IDENTITIES_FILE} -f ${UI_CONFIG_VALUES_FILE} --wait
