---
apiVersion: v2
name: validator
description: Canton Network Validator - NETWORK - validator
type: application
version: 1.0.0

dependencies:
  - name: splice-validator
    version: "CHART_VERSION"
    repository: "oci://ghcr.io/digital-asset/decentralized-canton-sync/helm"
    alias: validator
  - name: canton-validator-template
    version: "TEMPLATE_VERSION"
    repository: "file://../../templates/canton-validator-template"
    alias: template
