---
apiVersion: v2
name: global-domain-cometbft-MIGRATION_ID
description: Canton Network Super Validator - NETWORK - cometbft
type: application
version: 1.0.0

dependencies:
  - name: splice-cometbft
    version: "CHART_VERSION"
    repository: "oci://ghcr.io/digital-asset/decentralized-canton-sync/helm"
    alias: cometbft
  - name: canton-validator-template
    version: "TEMPLATE_VERSION"
    repository: "file://../../templates/canton-validator-template"
    alias: template
