---
apiVersion: v2
name: scan
description: Canton Network Super Validator - NETWORK - scan
type: application
version: 1.0.0

dependencies:
  - name: splice-scan
    version: "CHART_VERSION"
    repository: "oci://ghcr.io/digital-asset/decentralized-canton-sync/helm"
    alias: scan
  - name: canton-validator-template
    version: "TEMPLATE_VERSION"
    repository: "file://../../templates/canton-validator-template"
    alias: template

# helm install scan oci://ghcr.io/digital-asset/decentralized-canton-sync/helm/splice-scan -n sv --version ${CHART_VERSION} -f splice-node/examples/sv-helm/scan-values.yaml -f ${UI_CONFIG_VALUES_FILE} --wait
