#!/usr/bin/env python3
import os
import re
import shutil
import logging
from pathlib import Path
import yaml
import argparse

def setup_logging(debug=False):
    """Set up logging based on debug flag."""
    level = logging.DEBUG if debug else logging.INFO
    logging.basicConfig(level=level, format='%(asctime)s - %(levelname)s - %(message)s')

def load_env_vars(env_file_path):
    """Load environment variables from a file into a dictionary."""
    env_vars = {}
    with open(env_file_path, 'r') as f:
        for line in f:
            line = line.strip()
            if line:
                key, value = line.split('=', 1)
                env_vars[key.strip()] = value.strip()
    return env_vars

def replace_vars_in_string(text, env_vars):
    """Replace all occurrences of env vars in a string with their values."""
    original_text = text
    for key, value in env_vars.items():
        pattern = re.escape(key)
        if re.search(pattern, text):
            logging.debug(f"Replacing variable '{key}' with '{value}' in text: {text}")
            text = re.sub(pattern, value, text)
    return text

def get_non_template_alias(chart_yaml_path):
    """Extract the alias from Chart.yaml dependencies where alias is not 'template'."""
    with open(chart_yaml_path, 'r', encoding='utf-8') as f:
        chart_data = yaml.safe_load(f)
    
    dependencies = chart_data.get('dependencies', [])
    for dep in dependencies:
        alias = dep.get('alias')
        if alias and alias.strip() and alias != 'template':
            return alias
    return None

def process_yaml_content(src_path, dest_path, env_vars, alias=None, alias_prefix=False):
    """Process YAML file content, replacing env vars, optionally adding alias prefix."""
    with open(src_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    new_lines = []
    for line in lines:
        var_found = None
        var_start = None
        for key in env_vars:
            pattern = re.escape(key)
            match = re.search(pattern, line)
            if match:
                var_found = key
                var_start = match.start()
                break
        
        if var_found:
            before_var = line[:var_start]
            if '#' in before_var:
                new_lines.append(line)
            else:
                new_line = replace_vars_in_string(line, env_vars)
                logging.debug(f"Replacing line with variable '{var_found}' in {src_path}: {line.strip()} -> {new_line.strip()}")
                new_lines.append(new_line)
        else:
            new_lines.append(line)
    
    if alias and alias_prefix:
        indented_lines = ['  ' + line if line.strip() else line for line in new_lines]
        new_lines = [f'{alias}:\n'] + indented_lines
    
    with open(dest_path, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)

def process_file_content(src_path, dest_path, env_vars):
    """Process non-YAML file content, replacing env vars."""
    with open(src_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    new_lines = []
    for line in lines:
        var_found = None
        var_start = None
        for key in env_vars:
            pattern = re.escape(key)
            match = re.search(pattern, line)
            if match:
                var_found = key
                var_start = match.start()
                break
        
        if var_found:
            before_var = line[:var_start]
            if '#' in before_var:
                new_lines.append(line)
            else:
                new_line = replace_vars_in_string(line, env_vars)
                logging.debug(f"Replacing line with variable '{var_found}' in {src_path}: {line.strip()} -> {new_line.strip()}")
                new_lines.append(new_line)
        else:
            new_lines.append(line)
    
    with open(dest_path, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)

def find_git_repo(start_path):
    """Find the Git repository root by searching for .git directory."""
    current = Path(start_path).resolve()
    while current != current.parent:
        if (current / '.git').is_dir():
            return current
        current = current.parent
    return None

def update_gitignore(gitignore_path, new_entries):
    """Append new entries to .gitignore, avoiding duplicates."""
    existing_entries = set()
    if gitignore_path.exists():
        with open(gitignore_path, 'r', encoding='utf-8') as f:
            existing_entries = {line.strip().rstrip('/') for line in f if line.strip() and not line.startswith('#')}
    
    with open(gitignore_path, 'a', encoding='utf-8') as f:
        if existing_entries:
            f.write('\n')
        f.write('# Generated by canton-templating.py\n')
        for entry in sorted(new_entries):
            clean_entry = entry.rstrip('/')
            if clean_entry not in existing_entries:
                f.write(clean_entry + '\n')

def process_directory(src_dir, dest_dir, env_file, debug=False, alias_prefix=False, use_gitignore=False):
    """Process files and directories, replacing env vars, handling aliases, creating symlinks, and updating .gitignore."""
    setup_logging(debug)
    env_vars = load_env_vars(env_file)
    
    for symlink_path in Path(dest_dir).rglob('*'):
        if symlink_path.is_symlink():
            symlink_path.unlink()
            logging.debug(f"Removed existing symlink: {symlink_path}")
    
    Path(dest_dir).mkdir(parents=True, exist_ok=True)
    
    dir_mapping = {}
    created_symlinks = set()
    symlink_targets = set()
    
    for root, dirs, files in os.walk(src_dir):
        rel_path = os.path.relpath(root, src_dir)
        new_root = dest_dir if rel_path == '.' else os.path.join(dest_dir, replace_vars_in_string(rel_path, env_vars))
        Path(new_root).mkdir(parents=True, exist_ok=True)
        
        dir_mapping[new_root] = os.path.basename(root)
        
        alias = None
        chart_yaml_path = os.path.join(root, 'Chart.yaml')
        if os.path.exists(chart_yaml_path):
            alias = get_non_template_alias(chart_yaml_path)
        
        for file in files:
            src_file = os.path.join(root, file)
            new_filename = replace_vars_in_string(file, env_vars)
            dest_file = os.path.join(new_root, new_filename)
            
            if file.endswith(('.yaml', '.yml')):
                if (file in ('values.yaml', 'Chart.yaml', 'Chart.yml') and root == os.path.join(src_dir, rel_path)):
                    process_yaml_content(src_file, dest_path=dest_file, env_vars=env_vars)
                else:
                    process_yaml_content(src_file, dest_path=dest_file, env_vars=env_vars, alias=alias, alias_prefix=alias_prefix)
            else:
                process_file_content(src_file, dest_path=dest_file, env_vars=env_vars)
    
    processed_dirs = set()
    for root, dirs, _ in os.walk(dest_dir, topdown=False, followlinks=False):
        for dir_name in dirs:
            old_dir_path = os.path.join(root, dir_name)
            if old_dir_path in processed_dirs:
                continue
            
            src_dir_name = dir_mapping.get(old_dir_path, dir_name)
            new_dir_name = replace_vars_in_string(src_dir_name, env_vars)
            new_dir_path = os.path.join(root, new_dir_name)
            
            if old_dir_path != new_dir_path:
                shutil.move(old_dir_path, new_dir_path)
            
            if src_dir_name != new_dir_name:
                symlink_path = os.path.join(root, src_dir_name)
                if symlink_path in created_symlinks:
                    continue
                if os.path.exists(symlink_path):
                    os.remove(symlink_path)
                relative_target = os.path.basename(new_dir_path)
                try:
                    os.symlink(relative_target, symlink_path)
                    relative_symlink_path = os.path.relpath(symlink_path, dest_dir)
                    symlink_targets.add(relative_symlink_path)  # No trailing /
                    created_symlinks.add(symlink_path)
                except OSError as e:
                    logging.error(f"Failed to create symlink: {symlink_path}: {e}")
            
            processed_dirs.add(old_dir_path)
            processed_dirs.add(new_dir_path)
    
    if use_gitignore:
        git_repo = find_git_repo(dest_dir)
        if git_repo:
            gitignore_path = git_repo / '.gitignore'
            gitignore_entries = {os.path.join(os.path.relpath(dest_dir, git_repo), target.rstrip('/')) for target in symlink_targets}
            update_gitignore(gitignore_path, gitignore_entries)
        else:
            logging.error("No Git repository found; falling back to creating .gitignore in destination directory")
            gitignore_path = os.path.join(dest_dir, '.gitignore')
            with open(gitignore_path, 'w', encoding='utf-8') as f:
                f.write('# Automatically generated by canton-templating.py\n')
                for target in sorted(symlink_targets):
                    f.write(target + '\n')
    else:
        gitignore_path = os.path.join(dest_dir, '.gitignore')
        with open(gitignore_path, 'w', encoding='utf-8') as f:
            f.write('# Automatically generated by canton-templating.py\n')
            for target in sorted(symlink_targets):
                f.write(target + '\n')

def main():
    parser = argparse.ArgumentParser(
        description='Process templates with environment variables, Chart.yaml aliases, symlinks, and .gitignore.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
Mandatory arguments:
  src_dir             Source directory containing templates
  dest_dir            Destination directory for processed templates
  env_file            File containing environment variables

Optional arguments:
  -h, --help          Show this help message and exit
  --debug             Enable debug logging for string substitutions (default: False)
  --alias-prefix      Enable alias prefixing and reindentation in YAML files (default: False)
  --use-gitignore     Update the Git repository's .gitignore instead of creating one in dest_dir (default: False)
'''
    )
    parser.add_argument('src_dir', help='Source directory containing templates')
    parser.add_argument('dest_dir', help='Destination directory for processed templates')
    parser.add_argument('env_file', help='File containing environment variables')
    parser.add_argument('--debug', action='store_true', help='Enable debug logging for string substitutions')
    parser.add_argument('--alias-prefix', action='store_true', help='Enable alias prefixing and reindentation in YAML files')
    parser.add_argument('--use-gitignore', action='store_true', help='Update the Git repository\'s .gitignore instead of creating one in dest_dir')
    args = parser.parse_args()
    
    process_directory(
        args.src_dir,
        args.dest_dir,
        args.env_file,
        debug=args.debug,
        alias_prefix=args.alias_prefix,
        use_gitignore=args.use_gitignore
    )

if __name__ == '__main__':
    main()
