---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: utility-ui
  name: utility-ui
  namespace: NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utility-ui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: utility-ui
    spec:
      imagePullSecrets:
      - name: "JFROG_DA_UTILITY_REGCRED"
      containers:
      - name: utility-ui
        image: "$IMAGE_LOCATION:$IMAGE_VERSION"
        env:
        - name: AUTH_AUTHORITY
          value: "OIDC_AUTHORITY_URL"
        - name: AUTH_CLIENT_ID
          value: "$AUTH_CLIENT_ID"
        - name: AUTH_AUDIENCE
          value: "$AUTH_AUDIENCE"
        - name: UTILITY_APP_OPERATOR_PARTY_ID
          value: "$UTILITY_APP_OPERATOR_PARTY_ID"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 0.1
            memory: 240Mi
          limits:
            cpu: 1
            memory: 1536Mi
---
apiVersion: v1
kind: Service
metadata:
  name: utility-ui
  namespace: NAMESPACE
spec:
  selector:
    app: utility-ui
  ports:
  - name: http
    port: 8080
    protocol: TCP
